// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250806131016_UpdatetAtNullable")]
    partial class UpdatetAtNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Jwt", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Jwt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Expiration = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RefreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidGVzdEBtYWlsLmNvbSIsIm5iZiI6MTc1Mzg4NTQyOSwiZXhwIjoxNzU0NDkwMjI5LCJpc3MiOiJodHRwczovL3d3dy5lU2hvcC1hcGkuY29tIiwiYXVkIjoiZVNob3AtQXBpIn0.6byhPpfHXqbF2lDjOUgWoQ8v8O45Bnbh_R8W0pib2oA",
                            RefreshTokenExpiration = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QG1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidGVzdEBtYWlsLmNvbSIsIm5iZiI6MTc1Mzg4NTQyOSwiZXhwIjoxNzUzODkyNjI5LCJpc3MiOiJodHRwczovL3d3dy5lU2hvcC1hcGkuY29tIiwiYXVkIjoiZVNob3AtQXBpIn0.LJf4HNEJE8KLwnfBaVcO-MbJI_vXNAg_ZDdfkIwUoZ4",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2399.98m,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderStatus = 1,
                            PaymentMethod = 3,
                            TrackingNumber = "CD587DB4-C345-4D86-9D9C-F9C0A0BF50D3",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1499.99m,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 899.99m,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A powerful laptop",
                            ImageUrl = "https://example.com/laptop.jpg",
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 1499.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A modern smartphone",
                            ImageUrl = "https://example.com/phone.jpg",
                            IsDeleted = false,
                            Name = "Smartphone",
                            Price = 899.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A lightweight tablet",
                            ImageUrl = "https://example.com/tablet.jpg",
                            IsDeleted = false,
                            Name = "Tablet",
                            Price = 499.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "27-inch 4K monitor",
                            ImageUrl = "https://example.com/monitor.jpg",
                            IsDeleted = false,
                            Name = "Monitor",
                            Price = 329.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mechanical keyboard",
                            ImageUrl = "https://example.com/keyboard.jpg",
                            IsDeleted = false,
                            Name = "Keyboard",
                            Price = 89.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless mouse",
                            ImageUrl = "https://example.com/mouse.jpg",
                            IsDeleted = false,
                            Name = "Mouse",
                            Price = 49.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-cancelling headphones",
                            ImageUrl = "https://example.com/headphones.jpg",
                            IsDeleted = false,
                            Name = "Headphones",
                            Price = 199.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HD webcam",
                            ImageUrl = "https://example.com/webcam.jpg",
                            IsDeleted = false,
                            Name = "Webcam",
                            Price = 69.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laser printer",
                            ImageUrl = "https://example.com/printer.jpg",
                            IsDeleted = false,
                            Name = "Printer",
                            Price = 159.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wi-Fi 6 router",
                            ImageUrl = "https://example.com/router.jpg",
                            IsDeleted = false,
                            Name = "Router",
                            Price = 129.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1TB portable SSD",
                            ImageUrl = "https://example.com/ssd.jpg",
                            IsDeleted = false,
                            Name = "External SSD",
                            Price = 119.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness smartwatch",
                            ImageUrl = "https://example.com/smartwatch.jpg",
                            IsDeleted = false,
                            Name = "Smartwatch",
                            Price = 249.99m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bluetooth speakers",
                            ImageUrl = "https://example.com/speakers.jpg",
                            IsDeleted = false,
                            Name = "Speakers",
                            Price = 79.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic gaming chair",
                            ImageUrl = "https://example.com/chair.jpg",
                            IsDeleted = false,
                            Name = "Gaming Chair",
                            Price = 299.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB condenser microphone",
                            ImageUrl = "https://example.com/microphone.jpg",
                            IsDeleted = false,
                            Name = "Microphone",
                            Price = 109.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-end graphics card",
                            ImageUrl = "https://example.com/gpu.jpg",
                            IsDeleted = false,
                            Name = "Graphics Card",
                            Price = 799.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "20000mAh power bank",
                            ImageUrl = "https://example.com/powerbank.jpg",
                            IsDeleted = false,
                            Name = "Power Bank",
                            Price = 39.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Virtual reality headset",
                            ImageUrl = "https://example.com/vr.jpg",
                            IsDeleted = false,
                            Name = "VR Headset",
                            Price = 399.99m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Voice-controlled smart hub",
                            ImageUrl = "https://example.com/hub.jpg",
                            IsDeleted = false,
                            Name = "Smart Home Hub",
                            Price = 99.99m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Camera drone",
                            ImageUrl = "https://example.com/drone.jpg",
                            IsDeleted = false,
                            Name = "Drone",
                            Price = 599.99m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doe@mail.com",
                            Firstname = "John",
                            IsDeleted = false,
                            Lastname = "Doe",
                            Password = "$2a$12$Eju2KmPviy2UCJIUAlTtr.LFZ/DbdsFOOlN3YEoP5p30HLxwe1YXG"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Jwt", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Jwt")
                        .HasForeignKey("Domain.Entities.Jwt", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Jwt");
                });
#pragma warning restore 612, 618
        }
    }
}
